import = [
"~/.config/alacritty/catppuccin-frappe.toml"
]

live_config_reload = true

[font]
size = 10.0

[font.bold]
family = "Fira Code"
style = "Light"

[font.bold_italic]
family = "Fira Code"
style = "Light Italic"

[font.italic]
family = "Fira Code"
style = "Extra Light Italic"

[font.normal]
family = "Fira Code"
style = "ExtraLight"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.45

